window.ATLAS_PROJECTS = [
  {
    id: 'stormrelay',
    title: 'StormRelay',
    repo: 'https://github.com/DizzyZ7/StormRelay',
    category: 'platform',
    domain: 'SRE / Security Operations',
    status: 'Advanced build',
    year: '2026',
    featured: true,
    private: false,
    accent: '#7cf7c4',
    summary: 'Self-hosted event-correlation and incident-response control plane with durable automation, policy evaluation and a complete audit trail.',
    problem: 'Small product and operations teams need more than webhook forwarding: they need correlation, acknowledgement, recovery-aware automation and evidence for every decision.',
    architecture: ['Authenticated ingestion', 'NATS JetStream', 'Incident correlation', 'Policy engine', 'Durable runbooks', 'PostgreSQL audit'],
    stack: ['Go', 'PostgreSQL', 'NATS JetStream', 'OpenTelemetry', 'Prometheus', 'Grafana', 'Docker'],
    signals: ['Fail-closed RBAC', 'OIDC federation', 'Go/Python SDKs', 'Failure drills']
  },
  {
    id: 'signalbox',
    title: 'SignalBox',
    repo: 'https://github.com/DizzyZ7/SignalBox',
    category: 'backend',
    domain: 'Webhook Infrastructure',
    status: 'Production-oriented',
    year: '2026',
    featured: true,
    private: false,
    accent: '#57d9ff',
    summary: 'Compact Go webhook gateway with event persistence, deduplication, durable delivery, replay and an embedded admin console.',
    problem: 'Webhook handling is repeatedly rebuilt as fragile glue code. SignalBox turns it into a small self-hosted operational layer.',
    architecture: ['Public webhook', 'Token verification', 'Deduplication', 'PostgreSQL event log', 'Delivery queue', 'Telegram / HTTP'],
    stack: ['Go', 'PostgreSQL', 'pgx', 'Docker', 'OpenAPI', 'GitHub Actions'],
    signals: ['HMAC forwarding', 'SSRF guard', 'Prometheus metrics', 'Backup / restore']
  },
  {
    id: 'verdictmesh',
    title: 'VerdictMesh',
    repo: 'https://github.com/DizzyZ7/verdictmesh',
    category: 'ai',
    domain: 'Forecasting Intelligence',
    status: 'Paper-trading only',
    year: '2026',
    featured: true,
    private: false,
    accent: '#ff7ac8',
    summary: 'Evidence-grounded prediction-market intelligence platform with a forecasting council, deterministic consensus, risk controls and paper execution.',
    problem: 'Probabilistic decisions need evidence quality, disagreement tracking, deterministic risk boundaries and a complete audit trail before capital is involved.',
    architecture: ['Market ingestion', 'Evidence retrieval', 'Forecast council', 'Probability consensus', 'Risk engine', 'Paper broker'],
    stack: ['Python', 'FastAPI', 'PostgreSQL', 'Alembic', 'Claude', 'Prometheus', 'Docker'],
    signals: ['Schema-constrained agents', 'Fail-closed decisions', 'Order-book replay', 'Strict mypy']
  },
  {
    id: 'ai-memo',
    title: 'AI Memo',
    repo: 'https://github.com/DizzyZ7/AI-MEMO',
    category: 'product',
    domain: 'Voice-first SaaS / PWA',
    status: 'Cloud-ready MVP',
    year: '2026',
    featured: true,
    private: false,
    accent: '#b69cff',
    summary: 'Voice-first memo diary that turns thoughts into searchable notes, tasks, mood signals, repeated themes and weekly patterns.',
    problem: 'Fast thoughts are easy to capture but hard to organize, search and convert into useful follow-up actions.',
    architecture: ['Next.js PWA', 'Auth.js', 'tRPC', 'PostgreSQL + pgvector', 'QStash processing', 'R2 / email delivery'],
    stack: ['Next.js', 'React', 'TypeScript', 'Prisma', 'Supabase', 'OpenAI', 'QStash'],
    signals: ['Local demo mode', 'Semantic search', 'Usage limits', 'CI validation']
  },
  {
    id: 'homeledger',
    title: 'HomeLedger',
    repo: 'https://github.com/DizzyZ7/home-ledger',
    category: 'mobile',
    domain: 'Self-hosted Home Inventory',
    status: 'MVP foundation',
    year: '2026',
    featured: true,
    private: false,
    accent: '#ffd86a',
    summary: 'Flutter and FastAPI product for household inventory, warranty tracking, receipts and recurring maintenance.',
    problem: 'Household information is scattered across receipts, chats, galleries and memory exactly when it is needed most.',
    architecture: ['Flutter client', 'Mock-first mode', 'FastAPI service', 'JWT sessions', 'PostgreSQL', 'Docker Compose'],
    stack: ['Flutter', 'Dart', 'Riverpod', 'FastAPI', 'PostgreSQL', 'Alembic', 'Docker'],
    signals: ['RU / EN', 'Secure storage', 'Clean Architecture', 'Mobile + API tests']
  },
  {
    id: 'voice-runtime',
    title: 'Offline Voice Runtime',
    repo: 'https://github.com/DizzyZ7/voice_project_rhvoice',
    category: 'edge',
    domain: 'Voice / Edge / IoT',
    status: 'Multi-runtime prototype',
    year: '2026',
    featured: true,
    private: false,
    accent: '#64f0ff',
    summary: 'Offline STT/TTS platform with monolith and microservice modes, MQTT command transport, metrics and hardware integrations.',
    problem: 'Voice-controlled systems often depend on cloud APIs, making latency, privacy and offline operation difficult.',
    architecture: ['Vosk / Whisper STT', 'Command orchestrator', 'RHVoice / Piper TTS', 'MQTT transport', 'GPIO / Modbus', 'Prometheus / Grafana'],
    stack: ['Python', 'FastAPI', 'Vosk', 'faster-whisper', 'RHVoice', 'MQTT', 'Docker'],
    signals: ['Offline-first', 'Idempotency', 'Rate limiting', 'Raspberry Pi support']
  },
  {
    id: 'cashflow-copilot',
    title: 'SME Cashflow Copilot',
    repo: 'https://github.com/DizzyZ7/sme-cashflow-copilot',
    category: 'data',
    domain: 'Treasury Decision Support',
    status: 'Working MVP',
    year: '2026',
    featured: true,
    private: false,
    accent: '#91ff72',
    summary: 'Short-term liquidity forecasting, cash-gap detection and explainable recovery scenarios for small businesses.',
    problem: 'A founder needs to know what to do today to avoid running out of cash during the next two weeks.',
    architecture: ['CSV / Excel ingestion', 'Forecast engine', 'Risk detection', 'Scenario planner', 'Learning layer', 'UI / CLI / API'],
    stack: ['Python', 'Pandas', 'FastAPI', 'Streamlit', 'SQLite', 'Docker'],
    signals: ['What-if planning', 'Audit trail', 'Confidence scoring', 'JSON export']
  },
  {
    id: 'support-orchestrator',
    title: 'Intelligent Support Orchestrator',
    repo: 'https://github.com/DizzyZ7/Intelligent-Support-Orchestrator-with-RAG-Async-Processing',
    category: 'ai',
    domain: 'Customer Support Automation',
    status: 'Architecture demo',
    year: '2026',
    featured: false,
    private: false,
    accent: '#ff9a62',
    summary: 'Asynchronous RAG pipeline that answers customer tickets from internal documentation.',
    problem: 'Support answers need grounding in internal knowledge while LLM processing must not block the request path.',
    architecture: ['FastAPI gateway', 'Celery queue', 'Redis broker', 'Qdrant retrieval', 'LangChain RAG', 'Container stack'],
    stack: ['Python', 'FastAPI', 'Celery', 'Redis', 'Qdrant', 'LangChain'],
    signals: ['Async processing', 'Semantic search', 'Knowledge ingestion', 'Docker Compose']
  },
  {
    id: 'telconet',
    title: 'TelcoNet Guardian',
    repo: 'https://github.com/DizzyZ7/TelcoNet-Guardian',
    category: 'platform',
    domain: 'NOC Monitoring',
    status: 'Monitoring platform',
    year: '2026',
    featured: false,
    private: false,
    accent: '#62c6ff',
    summary: 'Async-first monitoring and automation platform for telecom and NOC scenarios.',
    problem: 'Network teams need a unified way to validate reachability, routing, telemetry and SLA behavior.',
    architecture: ['ICMP / TCP checks', 'BGP validation', 'SNMP telemetry', 'SLA engine', 'Alert routing', 'Metrics dashboards'],
    stack: ['Python', 'AsyncIO', 'FastAPI', 'SNMP', 'BGP', 'Prometheus', 'Grafana'],
    signals: ['Telegram alerts', 'Async probes', 'SLA tracking', 'Kubernetes direction']
  },
  {
    id: 'worknest',
    title: 'WorkNest API',
    repo: 'https://github.com/DizzyZ7/worknest-api',
    category: 'backend',
    domain: 'Workspace Backend',
    status: 'Production-style API',
    year: '2026',
    featured: false,
    private: false,
    accent: '#79d6b4',
    summary: 'Layered backend API foundation for workspace, project and task scenarios.',
    problem: 'Business products need a maintainable domain and migration strategy before UI complexity grows.',
    architecture: ['FastAPI entrypoint', 'Service layer', 'SQLAlchemy models', 'Alembic migrations', 'PostgreSQL', 'Pytest'],
    stack: ['Python', 'FastAPI', 'SQLAlchemy', 'PostgreSQL', 'Alembic', 'Docker'],
    signals: ['Clean boundaries', 'Migration flow', 'Container setup', 'Backend validation']
  },
  {
    id: 'qa-e2e',
    title: 'QA Microservices E2E',
    repo: 'https://github.com/DizzyZ7/qa-microservices-e2e-playwright-py',
    category: 'quality',
    domain: 'API → UI → DB Testing',
    status: 'Reusable framework',
    year: '2026',
    featured: false,
    private: false,
    accent: '#e9ff70',
    summary: 'End-to-end framework for validating complete microservice data paths across API, browser UI and PostgreSQL.',
    problem: 'Testing only one layer misses failures caused by contracts and state moving between services.',
    architecture: ['API data setup', 'UI scenario', 'Page objects', 'Database assertions', 'Cleanup isolation', 'Allure report'],
    stack: ['Python', 'Playwright', 'Pytest', 'PostgreSQL', 'Docker', 'Allure'],
    signals: ['Full data path', 'Repeatable cleanup', 'CI execution', 'Report artifacts']
  },
  {
    id: 'dodo-cv',
    title: 'Dodo CV Table Detector',
    repo: 'https://github.com/DizzyZ7/dodo-cv-table-detector',
    category: 'data',
    domain: 'Computer Vision',
    status: 'Lightweight CV prototype',
    year: '2026',
    featured: false,
    private: false,
    accent: '#ffb464',
    summary: 'ROI-based table occupancy detector producing annotated video, timelines and machine-readable summaries.',
    problem: 'Operational occupancy signals can often be extracted without training and maintaining a heavy ML model.',
    architecture: ['Video input', 'ROI calibration', 'Background model', 'Activity tracking', 'State classifier', 'CSV / JSON export'],
    stack: ['Python', 'OpenCV', 'NumPy', 'Pandas', 'CLI'],
    signals: ['No model training', 'Approach detection', 'Annotated output', 'Timeline export']
  },
  {
    id: 'telegram-chess',
    title: 'Telegram Chess App',
    repo: 'https://github.com/DizzyZ7/telegram_chess_app',
    category: 'product',
    domain: 'Telegram Mini App',
    status: 'Interactive product',
    year: '2026',
    featured: false,
    private: false,
    accent: '#a6a7ff',
    summary: 'Multiplayer chess experience designed for Telegram with a dedicated backend and compact game flows.',
    problem: 'Rich multiplayer interaction inside a messenger requires state synchronization and a mobile-first interface.',
    architecture: ['Telegram entry', 'Mini App UI', 'Game state', 'Move validation', 'Go backend', 'Session lifecycle'],
    stack: ['Go', 'Telegram Mini Apps', 'JavaScript', 'HTML', 'CSS'],
    signals: ['Multiplayer flow', 'Mobile-first', 'Game state', 'Messenger integration']
  },
  {
    id: 'antispam',
    title: 'Telegram Antispam Bot',
    repo: 'https://github.com/DizzyZ7/telegram-antispam-bot',
    category: 'automation',
    domain: 'Community Moderation',
    status: 'Operational bot',
    year: '2026',
    featured: false,
    private: false,
    accent: '#ff7070',
    summary: 'Moderation automation for Telegram communities with configurable enforcement workflows.',
    problem: 'Community moderation becomes inconsistent when warnings, temporary restrictions and bans are handled manually.',
    architecture: ['Message intake', 'Rule evaluation', 'Warning state', 'Timed restriction', 'Ban workflow', 'Persistence'],
    stack: ['Python', 'Telegram Bot API', 'SQLite', 'AsyncIO'],
    signals: ['Escalation rules', 'Persistent state', 'Automatic unmute', 'Admin controls']
  },
  {
    id: 'lead-bot',
    title: 'Concierge Lead Gen Bot',
    repo: 'https://github.com/DizzyZ7/Concierge-Lead-Gen-Bot',
    category: 'automation',
    domain: 'Lead Qualification',
    status: 'Product automation',
    year: '2026',
    featured: false,
    private: false,
    accent: '#ffcf5f',
    summary: 'Conversational lead qualification and routing flow for service businesses.',
    problem: 'Inbound leads need immediate qualification, structured context and consistent transfer into a sales workflow.',
    architecture: ['Conversation intake', 'Qualification state', 'Lead scoring', 'Contact capture', 'Routing', 'Operator handoff'],
    stack: ['Python', 'Telegram Bot API', 'FastAPI', 'PostgreSQL', 'Docker'],
    signals: ['Structured qualification', 'Handoff flow', 'Persistent funnel', 'Automation-first']
  },
  {
    id: 'ml-classifier',
    title: 'ML Text Classifier',
    repo: 'https://github.com/DizzyZ7/ml-text-classifier',
    category: 'data',
    domain: 'Applied Machine Learning',
    status: 'ML project',
    year: '2026',
    featured: false,
    private: false,
    accent: '#d48fff',
    summary: 'Text classification workflow covering data preparation, model training, evaluation and inference.',
    problem: 'Operational text streams need repeatable labeling and measurable model behavior rather than one-off notebooks.',
    architecture: ['Dataset loading', 'Text preprocessing', 'Feature pipeline', 'Model training', 'Evaluation', 'Inference'],
    stack: ['Python', 'scikit-learn', 'Pandas', 'NLP'],
    signals: ['Reproducible pipeline', 'Evaluation metrics', 'Inference flow', 'Model comparison']
  },
  {
    id: 'cs2-predictor',
    title: 'CS2 Skin Price Predictor',
    repo: 'https://github.com/DizzyZ7/CS2_Skin_Price_Predictor',
    category: 'data',
    domain: 'Gaming Market Analytics',
    status: 'Predictive prototype',
    year: '2026',
    featured: false,
    private: false,
    accent: '#f1a45d',
    summary: 'Price-analysis and prediction experiment for CS2 cosmetic-item markets.',
    problem: 'Highly variable game-item markets require clean historical data and explicit uncertainty around forecasts.',
    architecture: ['Market data', 'Feature extraction', 'Training set', 'Regression model', 'Evaluation', 'Forecast output'],
    stack: ['Python', 'Pandas', 'Machine Learning', 'Data Visualization'],
    signals: ['Domain-specific features', 'Price history', 'Model evaluation', 'Gaming analytics']
  },
  {
    id: 'work-task-flow',
    title: 'Work Task Flow',
    repo: 'https://github.com/DizzyZ7/WTF_Tast_Manager',
    category: 'product',
    domain: 'Project Management',
    status: 'Product foundation',
    year: '2026',
    featured: false,
    private: false,
    accent: '#8db6ff',
    summary: 'Self-hosted task and project-management platform focused on workspace and domain-first flows.',
    problem: 'Teams need an understandable project model before real-time collaboration and reporting are added.',
    architecture: ['Workspace model', 'Project domain', 'Task boards', 'Collaboration layer', 'Database', 'Deployment'],
    stack: ['TypeScript', 'Next.js', 'PostgreSQL', 'WebSocket', 'Docker'],
    signals: ['Domain-first design', 'Self-hosted direction', 'Real-time roadmap', 'MVP architecture']
  },
  {
    id: 'nerva',
    title: 'NERVA SYSTEMS',
    repo: 'https://github.com/DizzyZ7/NERVA-SYSTEMS',
    category: 'visual',
    domain: 'Automation Brand Experience',
    status: 'Digital experience',
    year: '2026',
    featured: false,
    private: true,
    accent: '#67f4d0',
    summary: 'Dark technology experience for an automation company, built around workflows assembling into one system.',
    problem: 'Complex automation services need to feel understandable, precise and operational rather than abstract.',
    architecture: ['Hero signal core', 'Workflow transformation', 'Systems lab', 'Case comparison', 'Process', 'Contact'],
    stack: ['Next.js', 'React', 'TypeScript', 'GSAP', 'Lenis'],
    signals: ['Interactive demo', 'Touch support', 'Reduced motion', 'Responsive motion']
  },
  {
    id: 'kora',
    title: 'KORA ARCHITECTS',
    repo: 'https://github.com/DizzyZ7/KORA-ARCHITECTS',
    category: 'visual',
    domain: 'Architectural Editorial',
    status: 'Digital experience',
    year: '2026',
    featured: false,
    private: true,
    accent: '#dc9369',
    summary: 'Warm editorial architecture site where drawings transform into spatial scenes.',
    problem: 'Architectural work needs atmosphere and structure without becoming a passive image gallery.',
    architecture: ['Model hero', 'Drawing reveal', 'Project rail', 'Principles', 'Process', 'Inquiry'],
    stack: ['HTML', 'CSS', 'JavaScript', 'GSAP', 'Lenis'],
    signals: ['Blueprint interaction', 'Horizontal gallery', 'Touch slider', 'Editorial layout']
  },
  {
    id: 'veil',
    title: 'VEIL',
    repo: 'https://github.com/DizzyZ7/VEIL',
    category: 'visual',
    domain: 'Luxury Fragrance',
    status: 'Digital experience',
    year: '2026',
    featured: false,
    private: true,
    accent: '#e1c7a0',
    summary: 'Cinematic monochrome fragrance experience using directed light, smoke and changing scent chapters.',
    problem: 'A fragrance cannot be smelled through a screen, so the interface must communicate texture, pace and memory.',
    architecture: ['Smoke canvas', 'Light interaction', 'Scent pyramid', 'Collection states', 'Atelier', 'Consultation'],
    stack: ['HTML', 'CSS', 'JavaScript', 'Canvas', 'GSAP'],
    signals: ['CSS bottle', 'Atmosphere switching', 'Touch collection', 'Luxury motion']
  },
  {
    id: 'blackline',
    title: 'BLACKLINE',
    repo: 'https://github.com/DizzyZ7/BLACKLINE',
    category: 'visual',
    domain: 'International Logistics',
    status: 'Digital experience',
    year: '2026',
    featured: false,
    private: true,
    accent: '#ff504c',
    summary: 'Neo-brutalist logistics interface with routes, hubs, tracking and an operational dispatch aesthetic.',
    problem: 'Logistics websites often list services but fail to communicate movement, control and reliability.',
    architecture: ['Route hero', 'Global hubs', 'Route builder', 'Live tracking', 'Services', 'Dispatch room'],
    stack: ['HTML', 'CSS', 'JavaScript', 'SVG', 'GSAP'],
    signals: ['Route simulation', 'Touch hubs', 'Tracking timeline', 'Neo-brutalist UI']
  },
  {
    id: 'orbita',
    title: 'ORBITA MEDICAL',
    repo: 'https://github.com/DizzyZ7/ORBITA-MEDICAL',
    category: 'visual',
    domain: 'Digital Clinic',
    status: 'Digital experience',
    year: '2026',
    featured: false,
    private: true,
    accent: '#71d8ff',
    summary: 'Soft-futuristic clinic experience with a care navigator and dynamic patient route.',
    problem: 'Medical interfaces must reduce uncertainty without pretending to diagnose or overwhelming the visitor.',
    architecture: ['Care map', 'Symptom navigator', 'Patient journey', 'Diagnostics', 'Specialists', 'Consultation'],
    stack: ['HTML', 'CSS', 'JavaScript', 'SVG', 'GSAP'],
    signals: ['Dynamic route', 'Touch-first', 'Accessible warning', 'Responsive UI']
  },
  {
    id: 'lumen',
    title: 'LUMEN ACADEMY',
    repo: 'https://github.com/DizzyZ7/LUMEN-ACADEMY',
    category: 'visual',
    domain: 'Technology Education',
    status: 'Digital experience',
    year: '2026',
    featured: false,
    private: true,
    accent: '#edff58',
    summary: 'Experimental learning platform with interactive tracks, coding challenges and a career simulator.',
    problem: 'Education sites should show the learning mechanism and evidence of skill, not only promises.',
    architecture: ['Code hero', 'Track lab', 'Learning loop', 'Challenge terminal', 'Projects', 'Career simulator'],
    stack: ['HTML', 'CSS', 'JavaScript', 'GSAP', 'Lenis'],
    signals: ['Interactive curriculum', 'Terminal challenges', 'Career proof', 'Mobile adaptation']
  },
  {
    id: 'volterra',
    title: 'VOLTERRA',
    repo: 'https://github.com/DizzyZ7/VOLTERRA',
    category: 'visual',
    domain: 'Energy Technology',
    status: 'Digital experience',
    year: '2026',
    featured: false,
    private: true,
    accent: '#a8f36a',
    summary: 'Cinematic engineering experience following energy from generation and storage to the grid and city.',
    problem: 'Integrated energy infrastructure needs a story that shows how every layer affects the next.',
    architecture: ['Reactor hero', 'Energy journey', 'Grid control', 'Platform rail', 'Impact model', 'Brief'],
    stack: ['HTML', 'CSS', 'JavaScript', 'SVG', 'GSAP'],
    signals: ['Energy path', 'Dispatch controls', 'Impact calculator', 'Responsive motion']
  },
  {
    id: 'neon',
    title: 'NEON DISTRICT',
    repo: 'https://github.com/DizzyZ7/NEON-DISTRICT',
    category: 'visual',
    domain: 'Digital Arts Festival',
    status: 'Digital experience',
    year: '2026',
    featured: false,
    private: true,
    accent: '#ff4fcb',
    summary: 'Experimental festival interface with a Canvas signal tunnel, mutable posters, zones, lineup and access system.',
    problem: 'A future-culture festival needs a digital identity that behaves like a live environment rather than a poster page.',
    architecture: ['Canvas tunnel', 'Frequency zones', 'Poster lab', 'Lineup', 'Program tunnel', 'Passes'],
    stack: ['HTML', 'CSS', 'JavaScript', 'Canvas', 'GSAP'],
    signals: ['Generative field', 'Mutable identity', 'Schedule states', 'Touch-first']
  }
];

window.ATLAS_CATEGORIES = [
  { id: 'all', label: 'All systems' },
  { id: 'platform', label: 'Platforms' },
  { id: 'backend', label: 'Backend' },
  { id: 'ai', label: 'AI / RAG' },
  { id: 'product', label: 'Products' },
  { id: 'automation', label: 'Automation' },
  { id: 'data', label: 'Data / CV' },
  { id: 'mobile', label: 'Mobile' },
  { id: 'edge', label: 'Voice / Edge' },
  { id: 'quality', label: 'Quality' },
  { id: 'visual', label: 'Digital experiences' }
];
